### PR TITLE
seperate out reference_system vs autoware specifics

### PR DESCRIPTION
**Pull request by flynneva**
Signed-off-by: Evan Flynn <evan.flynn@apex.ai>

separate out the core `reference_system` from the use of it to make `autoware_reference_system`

p.s. yes I know I misspelled `separate` 😓 

---
This change is [Reviewable](https://reviewable.io/reviews/apexai/reference-system-autoware/8)

### CODE REVIEW

**Comment by flynneva** [comment]
@landerU I cant seem to assign you as a reviewer so im tagging you here to review. your comments about renaming lead me here so thank you for that 😄 this new approach separates out the `reference_system` from the `autoware_reference_system` which should help us add other systems going forward.

**Comment by flynneva** [comment]
@elfenpiff tagged you here to get your input as well, no review needed but figured you might like to see what changes I  made

**Comment by flynneva** [comment]
going to go ahead and merge this as the other PR to the main `ros-realtime` group covers this change as well

**Comment by LanderU** [comment]
> @LanderU I cant seem to assign you as a reviewer so im tagging you here to review. your comments about renaming lead me here so thank you for that smile this new approach separates out the reference_system from the autoware_reference_system which should help us add other systems going forward.

@flynneva, yeah, I'm not part of the github Apex.AI organization :(

**Pull request merged**
